### ISSUE TITLE
Player tab list doesn't work on emortal.live but works on test server

### ISSUE THREAD

**Issue by NathanPenwill** [EmortalMC/BlockSumo#15]
https://media.discordapp.net/attachments/828976260662165505/829464822172090429/unknown.png

Should look like this ^

**Comment by SLLCoding** [comment]
Seems like a proxy-side issue, is there any custom to code to do with scoreboards on the proxy?

**Comment by NathanPenwill** [comment]
Fixed, turns out it was another plugin on my proxy.
