### ISSUE TITLE
Converting to MIT

### ISSUE THREAD

**Issue by emortaldev** [emortalmc/BlockSumo#27]
@GoldenStack @dylansoft
Do you agree to convert BlockSumo from AGPL to the MIT license?

**Comment by CommandCracker8** [comment]
Ayo why'd you assign me lmao

Anyway I have no opinion

**Comment by emortaldev** [comment]
was accident lol

**Comment by GoldenStack** [comment]
I agree.

**Comment by dylansoft** [comment]
Same here
